server:
  port: 8081
jwt:
  secret: hdgfkhfkghdfkghkjfdhgkdfgdurbnyrbgjdgjfhkhjfkhskbnsdkjbfksdhhkhkhkghkhgkjdhfkdfhgkdhjfgb
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
             
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG       
            